name: Deploy to Production Webserver
on:
  push:
    branches: ['prod']
jobs:
  restart-server:
    runs-on: ubuntu-latest
    steps:
      - name: restart
        uses: outsparkled/pterodactyl-power-action@v0.1.0
        with:
          panel-url: ${{ secrets.PANEL_URL }}
          server-id: ${{ secrets.SERVER_ID }}
          bearer-token: ${{ secrets.BEARER_TOKEN }}
          power-action: 'restart'
